---
name: Docker image build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io

    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Check out pbg-ld repo
        uses: actions/checkout@v2
        with:
          repository: candYgene/pbg-ld
          path: './pbg-ld/src'
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set docker image names
        run: |
          echo "VOS_IMG=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/virtuoso:dev" >> ${GITHUB_ENV}
          echo "PBG_IMG=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/pbg-ld:dev" >> ${GITHUB_ENV}
      - name: Build docker image 1
        working-directory: virtuoso
        run: |
          docker build -t $VOS_IMG .
      - name: Fetch RDF data from Zenodo
        working-directory: pbg-ld
        run: |
          wget -nv https://zenodo.org/record/7641017/files/pbg-ld.zip
          unzip pbg-ld.zip
      - name: Build docker image 2
        working-directory: pbg-ld
        run: |
          ls -alh
          docker build -t $PBG_IMG .
      - name: Publish docker images
        run: |
          docker push $VOS_IMG
          docker push $PBG_IMG