---
name: Docker image build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      TAG: dev
      NAME: virtuoso
      FILE_PATH: virtuoso/Dockerfile

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set Docker image name
        run: |
          echo "IMG_TAG=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/${NAME}:${TAG}" >> ${GITHUB_ENV}
      - name: Build Docker image
        run: |
          docker build -t $IMG_TAG -f $FILE_PATH
      - name: Push Docker image to registry
        run: docker push $IMG_TAG
