---
name: Docker build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMG_TAG: latest
      VOS_VERSION: v7.2.8
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set docker image name
        run: |
          echo "VOS_IMG=${REGISTRY}/${GITHUB_REPOSITORY_OWNER,,}/virtuoso:${IMG_TAG}" >> ${GITHUB_ENV}
      - name: Build docker image
        working-directory: virtuoso
        run: |
          docker build -t $VOS_IMG --build-arg ${VOS_VERSION} .
      - name: Publish docker images
        run: |
          docker push $VOS_IMG
